### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by JanGunheD** [Lynxmotion/LSS_Library_Python#1] opened 2020-08-09 17:41 UTC
in lss.py, in the read functions, LSS.bus.read_until waits until the timeout, slowing reading down significantly. This can be fixed by adding .encode('utf-8') to lssc.LSS_CommandEnd:

data = LSS.bus.read_until(lssc.LSS_CommandEnd.encode('utf-8'))

**Comment by rbscharette** [comment] 2020-08-10 15:36
Thanks for the info. Do you have more info on the delays caused by **read_until()** as it is currently used? Does the current use cause it to always wait until timeout?
If so, feel free to create a pull request with the relevant fix for us to test (with notes or instructions as needed).

**Comment by JanGunheD** [comment] 2020-08-11 16:02
Yes, the problem is, that the whole communication from and to the servos seems to be UTF8-coded, which is respected in the code. But in the read_until statement, the "lssc.LSS_CommandEnd" is ASCII-coded, so it is never found. This way, read_until always waits until the timeout occurs. That is not noticed so easily as the timeout is currently set to 0.1s. If you set it to 1 or more seconds, you can see that the response always takes exactly as long as the timeout is set. On the other hand, before the timeout, the other data that is received before lssc.LSS_CommandEnd is already enough to interpret the answer, so the asked for values are correctly received.

The solution is to use lssc.LSS_CommandEnd.encode('utf-8') to convert also this command end char to UTF8, so it is correctly found way before the timeout. To test this, you can make this change and set the timeout a lot higher, the communication response will still be a lot quicker.

I will make a pull request later today.

**Comment by rbscharette** [comment] 2020-08-11 16:39
This is quite interesting, since a ASCII \r (0xD or 13 in dec) should be the same in UTG-8 encoding since the most significant bit is 0. Furthermore, as far as I know, Python should be using UTF-8 encoding by default unless told otherwise, so all the constants in lssc.py should be treated as such already.

While your proposed fix most likely do exactly what you mention and fixes the issue of waiting on read_until()'s timeout, I'm now quite curious as to why that is an issue at all. I'll probably have to look into read_until() from pyserial and see if I can figure out why that is happening. Do you happen to have any more ideas on this and its cause(s)?

**Comment by rbscharette** [comment] 2020-08-11 16:42
Hmm, this may offer some more info:  https://github.com/pyserial/pyserial/issues/181#issuecomment-521170931
> The expected string in read_until must be a byte array. Then is everything okay.
> e.g. response = s.read_until('> '.encode('utf-8')).decode('utf-8')

That is an interesting requirement.

**Comment by JanGunheD** [comment] 2020-08-11 19:23
I found that reference, too, but seemingly the byte-array thing was not necessary. Or it is created by encode....

**Comment by rbscharette** [comment] 2020-08-11 19:32
Yeah, that would be my guess as to why it fixes the issue.

**Comment by rbscharette** [comment] 2020-08-12 14:06
Thanks again for the PR.
I'll close this now since it was resolved in https://github.com/Lynxmotion/LSS_Library_Python/pull/2

**Closed as completed by rbscharette** 2020-08-12 14:06 UTC
Labels: bug, resolved
